import Head from 'next/head'

export default function Home() {
  return (
    <div className="min-h-full py-0 px-2 flex flex-col items-center justify-center h-screen bg-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-6 max-w-sm mx-auto my-auto bg-white rounded-xl shadow-md flex items-center space-x-4">
        <div>
          <div className="text-xl font-medium text-black">Hello World</div>
          <p className="text-gray-500">This card uses Tailwind CSS</p>
        </div>
      </div>
    </div>
  )
}
